# Generated by Django 4.0.4 on 2023-04-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_rename_product_owner_name_sell_product_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='Product_name',
            new_name='Productname',
        ),
        migrations.RenameField(
            model_name='sell',
            old_name='Product_owner',
            new_name='Productowner',
        ),
    ]
