# Generated by Django 4.0.4 on 2023-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_sales_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='mobilenum',
            field=models.CharField(default='', max_length=10),
        ),
    ]
