# Generated by Django 4.0.4 on 2023-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_sales_mobilenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='phnum',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='pin',
            field=models.CharField(max_length=6),
        ),
    ]
