# Generated by Django 4.0.4 on 2023-04-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='Product_owner_name',
            new_name='Product_owner',
        ),
    ]
