# Generated by Django 4.0.4 on 2023-04-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_service_sales_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
