# Generated by Django 4.0.4 on 2023-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_sales_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
